from manim import *
class m(Scene):
    def construct(self):
        text_for_banner = 'Multiplication'
        t1 = Text(text_for_banner, color = YELLOW)
        sr1 = SurroundingRectangle(t1, color = YELLOW)
        t2 = Text("Repeated Addition", color = RED)
        u1 = Underline(t2, color = RED)
        g1 = VGroup(t2, u1)
        t_5 = Text("5", color = BLUE).shift(LEFT*4).scale(3)
        t_54 = Text("5+5+5+5", color = BLUE).scale(3)
        t_54num = Text("1     2     3     4").shift(UP*1.75).scale(2)
        t_5i4 = Text("4", color = BLUE).shift(UP*1.75,RIGHT*1).scale(3)
        t_5i5 = Text("5", color = BLUE).shift(LEFT*1).scale(3)
        g2 = VGroup(t_5i5, t_5i4)
        t3 = Text("5 x 4", color = BLUE).scale(3)
        r1 = Rectangle(height = 4, width = 5, fill_opacity = 1)
        t5 = Text("Example:", color = YELLOW).shift(UP*3)
        u2 = Underline(t5, color = YELLOW)
        g3 = VGroup(t5, u2)
        g4 = VGroup(t1, sr1)
        hl1 = Line(start=[-2.5, 1, 0], end=[2.5, 1, 0], color=WHITE, stroke_width=2)
        hl2 = Line(start=[-2.5, 0, 0], end=[2.5, 0, 0], color=WHITE, stroke_width=2)
        hl3 = Line(start=[-2.5, -1, 0], end=[2.5, -1, 0], color=WHITE, stroke_width=2)
        hl = VGroup(hl1, hl2, hl3)
        vl1 = Line(start=[-1.5, 2, 0], end=[-1.5, -2, 0], color=WHITE, stroke_width=4)
        vl2 = Line(start=[-0.5, 2, 0], end=[-0.5, -2, 0], color=WHITE, stroke_width=4)
        vl3 = Line(start=[0.5, 2, 0], end=[0.5, -2, 0], color=WHITE, stroke_width=4)
        vl4 = Line(start=[1.5, 2, 0], end=[1.5, -2, 0], color=WHITE, stroke_width=4)
        vl = VGroup(vl1, vl2, vl3, vl4)
        rn = Text("1    2    3    4    5").shift(UP*1.5)
        r2 = Rectangle(width = 5, height = 1).shift(UP*1.5)
        ri2 = Text("1").shift(UP*1.5, LEFT*3.5)
        r3 = Rectangle(width = 5, height = 1).shift(UP*0.5)
        ri3 = Text("2").shift(UP*0.5, LEFT*3.5)
        r4 = Rectangle(width = 5, height = 1).shift(DOWN*0.5)
        ri4 = Text("3").shift(UP*-0.5, LEFT*3.5)
        r5 = Rectangle(width = 5, height = 1).shift(DOWN*1.5)
        ri5 = Text("4").shift(UP*-1.5, LEFT*3.5)
        rg1 = VGroup(r2, r3, r4, r5)
        ri = VGroup(ri2, ri3, ri4, ri5)
        cn = Text("5", color = BLUE).shift(UP*3).scale(2)
        rnum = Text("4", color = BLUE).shift(LEFT*3.5).scale(2)
        sl = VGroup(cn, rnum)
        fq = Text("5 x 4 = 5+5+5+5", color = BLUE).scale(2)
        faq1 = Text("5+5+5+5", color = BLUE).scale(2)
        faq2 = Text("10+5+5", color = BLUE).scale(2)
        faq3 = Text("15+5", color = BLUE).scale(2)
        faq4 = Text("20", color = RED).scale(3)
        faqb = SurroundingRectangle(faq4, color = RED)
        faq4b = VGroup(faq4, faqb)
        f = Text("5 x 4 = 20").scale(4)
        f2 = Text("Multiplication!").scale(3)
        self.play(FadeIn(t1, run_time=1.5))
        self.play(Write(sr1))
        self.play(t1.animate.shift(UP*3), sr1.animate.shift(UP*3))
        self.wait(1)
        self.play(Write(g1))
        self.wait(1)
        self.play(ReplacementTransform(g1, t_5))
        self.play(ReplacementTransform(t_5, t_54))
        self.play(Write(t_54num), run_time = 1.5)
        self.play(Indicate(t_54num[3], color = RED))
        self.play(ReplacementTransform(t_54num, t_5i4))
        self.play(ReplacementTransform(t_54, t_5i5))
        self.play(ReplacementTransform(g2, t3))
        self.wait(2)
        self.play(FadeOut(t3), ReplacementTransform(g4, g3))
        self.play(Write(r1), g3.animate.shift(UP*4))
        self.wait(2)
        self.play(r1.animate.set_fill(opacity = 0), run_time=1)
        self.play(Write(hl), Write(vl))
        self.play(Write(rg1), Write(rn))
        self.play(Write(ri))
        self.play(Indicate(r2, color = RED), Indicate(ri2, color = RED))
        self.play(Indicate(r3, color = RED), Indicate(ri3, color = RED), ReplacementTransform(rn, cn))
        self.play(Indicate(r4, color = RED), Indicate(ri4, color = RED))
        self.play(Indicate(r5, color = RED), Indicate(ri5, color = RED))
        self.play(ReplacementTransform(ri, rnum))
        self.play(FadeOut(r1, r2, r3, r4, r5, vl1, vl2, vl3, vl4, hl1, hl2, hl3))
        self.play(ReplacementTransform(sl, fq[0:3]))
        self.wait(0.5)
        self.play(Write(fq[3:]))
        self.wait(1)
        self.play(FadeOut(fq))
        self.play(Write(faq1))
        self.wait(0.5)
        self.play(ReplacementTransform(faq1, faq2))
        self.wait(0.5)
        self.play(ReplacementTransform(faq2, faq3))
        self.wait(0.5)
        self.play(ReplacementTransform(faq3, faq4))
        self.wait(0.5)
        self.play(Write(faqb))
        self.wait(2)
        self.play(FadeOut(faq4b))
        self.play(Write(f))
        self.wait(3)
        self.play(FadeOut(f))
        self.play(Write(f2))
        self.wait(5)